// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListResult<T> = {
  page: bigint;
  per_page: bigint;
  total_items: bigint;
  total_pages: bigint;
  items: Array<T>;
};
