// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Users = { id: string, name: string, email: string, created: string, updated: string, };
