/**
 * Auto-generated Zod schema for BillingManagementAccountTransactions
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import {
  fieldRegistry,
  fieldSetRegistry,
} from "@/components/ui/autoform-tanstack/types";
import { RelationFieldProps } from "@/components/ui/forms/fields";
import { Collections } from "@/lib/pb.types";

export const AccountTransactionsSchema = z
  .object({
    id: z.string().register(fieldRegistry, {
      id: "id",
      type: "field",
      inputType: "text",
      label: "Transaction ID",
      description: "Unique identifier for the transaction",
      props: {
        disabled: true,
      },
    }),
    clientAccount: z.string().register(fieldRegistry, {
      type: "field",
      id: "clientAccount",
      inputType: "relation",
      label: "Client Account",
      description: "Client account for this transaction",
      props: {
        collectionName: Collections.BillingManagementClientAccounts,
        relationshipName: "clientAccount",
        displayField: "id",
      } as RelationFieldProps<any>,
    }),
    type: z
      .enum(["credit", "debit", "top-up", "refund", "adjustment", "fee"])
      .register(fieldRegistry, {
        id: "type",
        type: "field",
        inputType: "select",
        label: "Type",
        description: "Type of transaction",
        props: {
          options: [
            { label: "Credit", value: "credit" },
            { label: "Debit", value: "debit" },
            { label: "Top-up", value: "top-up" },
            { label: "Refund", value: "refund" },
            { label: "Adjustment", value: "adjustment" },
            { label: "Fee", value: "fee" },
          ],
        },
      }),
    amount: z.number().register(fieldRegistry, {
      id: "amount",
      type: "field",
      inputType: "number",
      label: "Amount",
      description: "Transaction amount",
      props: {
        placeholder: "0.00",
        min: 0,
      },
    }),
    runningBalance: z
      .number()
      .optional()
      .register(fieldRegistry, {
        id: "runningBalance",
        type: "field",
        inputType: "number",
        label: "Running Balance",
        description: "Account balance after transaction",
        props: {
          placeholder: "0.00",
        },
      }),
    transactionDate: z.iso.date().optional().register(fieldRegistry, {
      id: "transactionDate",
      type: "field",
      inputType: "date",
      label: "Transaction Date",
      description: "Date of the transaction",
    }),
    processedBy: z
      .string()
      .optional()
      .register(fieldRegistry, {
        type: "field",
        id: "processedBy",
        inputType: "relation",
        label: "Processed By",
        description: "User who processed the transaction",
        props: {
          collectionName: Collections.Users,
          relationshipName: "processedBy",
          displayField: "name",
        } as RelationFieldProps<any>,
      }),
    referenceNumber: z
      .string()
      .optional()
      .register(fieldRegistry, {
        id: "referenceNumber",
        type: "field",
        inputType: "text",
        label: "Reference Number",
        description: "Transaction reference number",
        props: {
          placeholder: "REF-001",
        },
      }),
    created: z.iso
      .datetime()
      .optional()
      .register(fieldRegistry, {
        id: "created",
        type: "field",
        inputType: "date",
        label: "Created At",
        description: "Timestamp when created",
        props: {
          disabled: true,
        },
      }),
    updated: z.iso
      .datetime()
      .optional()
      .register(fieldRegistry, {
        id: "updated",
        type: "field",
        inputType: "date",
        label: "Updated At",
        description: "Timestamp when last updated",
        props: {
          disabled: true,
        },
      }),
  })
  .register(fieldSetRegistry, { separator: true });

export type AccountTransactions = z.infer<typeof AccountTransactionsSchema>;
