/**
 * Auto-generated Zod schema for BillingManagementRateCards
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";

export const RateCardsSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.enum([
    "shipping",
    "storage",
    "fulfillment",
    "handling",
    "insurance",
    "customs",
    "packaging",
    "returns",
  ]),
  isActive: z.boolean().optional(),
  validFrom: z.coerce.date().optional(),
  validTo: z.coerce.date().optional(),
  description: z.string().optional(),
  createdBy: z.string().optional(),
  created: z.iso.datetime().optional(),
  updated: z.iso.datetime().optional(),
});

export type RateCards = z.infer<typeof RateCardsSchema>;
