//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("dms")
    }
    fn table_name(&self) -> &str {
        "driver_locations"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, async_graphql::SimpleObject)]
pub struct Model {
    pub id: Uuid,
    pub driver_id: Uuid,
    pub latitude: f32,
    pub longitude: f32,
    pub altitude: Option<f32>,
    pub accuracy: Option<f32>,
    pub speed_kmh: Option<f32>,
    pub heading: Option<f32>,
    pub timestamp: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    DriverId,
    Latitude,
    Longitude,
    Altitude,
    Accuracy,
    SpeedKmh,
    Heading,
    Timestamp,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Drivers,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::DriverId => ColumnType::Uuid.def(),
            Self::Latitude => ColumnType::Float.def(),
            Self::Longitude => ColumnType::Float.def(),
            Self::Altitude => ColumnType::Float.def().null(),
            Self::Accuracy => ColumnType::Float.def().null(),
            Self::SpeedKmh => ColumnType::Float.def().null(),
            Self::Heading => ColumnType::Float.def().null(),
            Self::Timestamp => ColumnType::DateTime.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Drivers => Entity::belongs_to(super::drivers::Entity)
                .from(Column::DriverId)
                .to(super::drivers::Column::Id)
                .into(),
        }
    }
}

impl Related<super::drivers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Drivers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
