# Development override for Docker Compose
#
# This file overrides the app service to build from source instead of using a prebuilt image.
# Usage:
#   docker compose -f compose.yaml -f compose.dev.yaml up
#
# This will build the app service from the Dockerfile in the current directory.

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port for sending emails
      - "8025:8025" # Web interface for viewing emails
  postgres:
    image: postgres:17.2-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DOCKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DOCKER_POSTGRES_DB}

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${DOCKER_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${DOCKER_MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:

