//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::TransactionTypeEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "billing", table_name = "account_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub client_account_id: Uuid,
    pub r#type: TransactionTypeEnum,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))", nullable)]
    pub running_balance: Option<Decimal>,
    pub source_record_id: Option<Uuid>,
    pub source_record_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub reference_number: Option<String>,
    pub transaction_date: Option<DateTime>,
    pub processed_by_user_id: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::client_accounts::Entity",
        from = "Column::ClientAccountId",
        to = "super::client_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ClientAccounts,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ProcessedByUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::client_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientAccounts.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
