ALTER TABLE "ims"."inbound_shipment_items" ALTER COLUMN "inbound_shipment_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inbound_shipment_items" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inbound_shipments" ALTER COLUMN "client_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inbound_shipments" ALTER COLUMN "warehouse_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_adjustments" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_adjustments" ALTER COLUMN "warehouse_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_adjustments" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_batches" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_levels" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_levels" ALTER COLUMN "warehouse_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_levels" ALTER COLUMN "location_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."inventory_levels" ALTER COLUMN "batch_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."outbound_shipment_items" ALTER COLUMN "outbound_shipment_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."outbound_shipment_items" ALTER COLUMN "sales_order_item_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."outbound_shipment_items" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."outbound_shipment_items" ALTER COLUMN "batch_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."outbound_shipments" ALTER COLUMN "sales_order_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."outbound_shipments" ALTER COLUMN "warehouse_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."reorder_points" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."reorder_points" ALTER COLUMN "warehouse_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."return_items" ALTER COLUMN "return_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."return_items" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."returns" ALTER COLUMN "sales_order_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."returns" ALTER COLUMN "client_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."sales_order_items" ALTER COLUMN "sales_order_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."sales_order_items" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."sales_orders" ALTER COLUMN "client_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."sales_orders" ALTER COLUMN "crm_opportunity_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."stock_transfers" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."stock_transfers" ALTER COLUMN "source_warehouse_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ims"."stock_transfers" ALTER COLUMN "destination_warehouse_id" SET DATA TYPE uuid;