//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::PermissionStatus;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("org")
    }
    fn table_name(&self) -> &str {
        "department_permissions"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub department_id: Uuid,
    pub resource: String,
    pub action: PermissionStatus,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    DepartmentId,
    Resource,
    Action,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    DepartmentUserPermissions,
    Departments,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::DepartmentId => ColumnType::Uuid.def(),
            Self::Resource => ColumnType::Text.def(),
            Self::Action => PermissionStatus::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::DepartmentUserPermissions => {
                Entity::has_many(super::department_user_permissions::Entity).into()
            }
            Self::Departments => Entity::belongs_to(super::departments::Entity)
                .from(Column::DepartmentId)
                .to(super::departments::Column::Id)
                .into(),
        }
    }
}

impl Related<super::department_user_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepartmentUserPermissions.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
