//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::DriverStatus;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("org")
    }
    fn table_name(&self) -> &str {
        "drivers"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub employee_id: String,
    pub first_name: String,
    pub last_name: String,
    pub license_number: String,
    pub phone_number: String,
    pub email: String,
    pub hire_date: Date,
    pub status: DriverStatus,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    EmployeeId,
    FirstName,
    LastName,
    LicenseNumber,
    PhoneNumber,
    Email,
    HireDate,
    Status,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::EmployeeId => ColumnType::String(StringLen::N(20u32)).def().unique(),
            Self::FirstName => ColumnType::String(StringLen::N(50u32)).def(),
            Self::LastName => ColumnType::String(StringLen::N(50u32)).def(),
            Self::LicenseNumber => ColumnType::String(StringLen::N(30u32)).def().unique(),
            Self::PhoneNumber => ColumnType::String(StringLen::N(20u32)).def(),
            Self::Email => ColumnType::String(StringLen::N(320u32)).def().unique(),
            Self::HireDate => ColumnType::Date.def(),
            Self::Status => DriverStatus::db_type().get_column_type().to_owned().def(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
