//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::CrmContactStatus;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "crm_contacts"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub phone_number: Option<String>,
    pub job_title: Option<String>,
    pub lead_source: Option<String>,
    pub status: CrmContactStatus,
    pub birth_date: Option<Date>,
    pub company_id: Option<Uuid>,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
    pub address_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq, Eq, async_graphql::Enum)]
pub enum Column {
    Id,
    FirstName,
    LastName,
    Email,
    PhoneNumber,
    JobTitle,
    LeadSource,
    Status,
    BirthDate,
    CompanyId,
    Created,
    Updated,
    AddressId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CrmCampaignContacts,
    CrmCases,
    CrmCompanies,
    CrmInteractions,
    CrmInvoices,
    CrmLeads,
    CrmNotifications,
    CrmOpportunities,
    LmsAddresses,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::FirstName => ColumnType::String(StringLen::N(100u32)).def(),
            Self::LastName => ColumnType::String(StringLen::N(100u32)).def(),
            Self::Email => ColumnType::String(StringLen::N(320u32)).def().unique(),
            Self::PhoneNumber => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::JobTitle => ColumnType::String(StringLen::N(150u32)).def().null(),
            Self::LeadSource => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Status => CrmContactStatus::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::BirthDate => ColumnType::Date.def().null(),
            Self::CompanyId => ColumnType::Uuid.def().null(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
            Self::AddressId => ColumnType::Uuid.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CrmCampaignContacts => {
                Entity::has_many(super::crm_campaign_contacts::Entity).into()
            }
            Self::CrmCases => Entity::has_many(super::crm_cases::Entity).into(),
            Self::CrmCompanies => Entity::belongs_to(super::crm_companies::Entity)
                .from(Column::CompanyId)
                .to(super::crm_companies::Column::Id)
                .into(),
            Self::CrmInteractions => Entity::has_many(super::crm_interactions::Entity).into(),
            Self::CrmInvoices => Entity::has_many(super::crm_invoices::Entity).into(),
            Self::CrmLeads => Entity::has_many(super::crm_leads::Entity).into(),
            Self::CrmNotifications => Entity::has_many(super::crm_notifications::Entity).into(),
            Self::CrmOpportunities => Entity::has_many(super::crm_opportunities::Entity).into(),
            Self::LmsAddresses => Entity::belongs_to(super::lms_addresses::Entity)
                .from(Column::AddressId)
                .to(super::lms_addresses::Column::Id)
                .into(),
        }
    }
}

impl Related<super::crm_campaign_contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmCampaignContacts.def()
    }
}

impl Related<super::crm_cases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmCases.def()
    }
}

impl Related<super::crm_companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmCompanies.def()
    }
}

impl Related<super::crm_interactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmInteractions.def()
    }
}

impl Related<super::crm_invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmInvoices.def()
    }
}

impl Related<super::crm_leads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmLeads.def()
    }
}

impl Related<super::crm_notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmNotifications.def()
    }
}

impl Related<super::crm_opportunities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmOpportunities.def()
    }
}

impl Related<super::lms_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsAddresses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
