//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "crm_invoice_line_items"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub invoice_id: Uuid,
    pub shipment_id: Option<Uuid>,
    pub description: String,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub line_total: Option<Decimal>,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    InvoiceId,
    ShipmentId,
    Description,
    Quantity,
    UnitPrice,
    LineTotal,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CrmInvoices,
    LmsShipments,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::InvoiceId => ColumnType::Uuid.def(),
            Self::ShipmentId => ColumnType::Uuid.def().null(),
            Self::Description => ColumnType::String(StringLen::N(500u32)).def(),
            Self::Quantity => ColumnType::Decimal(Some((10u32, 2u32))).def(),
            Self::UnitPrice => ColumnType::Decimal(Some((10u32, 2u32))).def(),
            Self::LineTotal => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CrmInvoices => Entity::belongs_to(super::crm_invoices::Entity)
                .from(Column::InvoiceId)
                .to(super::crm_invoices::Column::Id)
                .into(),
            Self::LmsShipments => Entity::belongs_to(super::lms_shipments::Entity)
                .from(Column::ShipmentId)
                .to(super::lms_shipments::Column::Id)
                .into(),
        }
    }
}

impl Related<super::crm_invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmInvoices.def()
    }
}

impl Related<super::lms_shipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsShipments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
