//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::LmsDeliveryStatus;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "lms_route_shipments"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub route_id: Uuid,
    pub shipment_id: Uuid,
    pub sequence_number: i32,
    pub delivery_date: Date,
    pub estimated_delivery: Option<DateTimeWithTimeZone>,
    pub actual_delivery: Option<DateTimeWithTimeZone>,
    pub delivery_status: LmsDeliveryStatus,
    pub signature_required: bool,
    pub recipient_signature: Option<String>,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq, Eq, async_graphql::Enum)]
pub enum Column {
    Id,
    RouteId,
    ShipmentId,
    SequenceNumber,
    DeliveryDate,
    EstimatedDelivery,
    ActualDelivery,
    DeliveryStatus,
    SignatureRequired,
    RecipientSignature,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    LmsRoutes,
    LmsShipments,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RouteId => ColumnType::Uuid.def(),
            Self::ShipmentId => ColumnType::Uuid.def(),
            Self::SequenceNumber => ColumnType::Integer.def(),
            Self::DeliveryDate => ColumnType::Date.def(),
            Self::EstimatedDelivery => ColumnType::TimestampWithTimeZone.def().null(),
            Self::ActualDelivery => ColumnType::TimestampWithTimeZone.def().null(),
            Self::DeliveryStatus => LmsDeliveryStatus::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::SignatureRequired => ColumnType::Boolean.def(),
            Self::RecipientSignature => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::LmsRoutes => Entity::belongs_to(super::lms_routes::Entity)
                .from(Column::RouteId)
                .to(super::lms_routes::Column::Id)
                .into(),
            Self::LmsShipments => Entity::belongs_to(super::lms_shipments::Entity)
                .from(Column::ShipmentId)
                .to(super::lms_shipments::Column::Id)
                .into(),
        }
    }
}

impl Related<super::lms_routes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsRoutes.def()
    }
}

impl Related<super::lms_shipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsShipments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
