//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::LmsAddressType;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "lms_addresses"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub address_line1: String,
    pub address_line2: Option<String>,
    pub city: String,
    pub state: String,
    pub postal_code: String,
    pub country: String,
    pub address_type: LmsAddressType,
    pub is_validated: bool,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    AddressLine1,
    AddressLine2,
    City,
    State,
    PostalCode,
    Country,
    AddressType,
    IsValidated,
    Latitude,
    Longitude,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CrmCompanies,
    CrmContacts,
    LmsTransportationProviders,
    LmsWarehouses,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::AddressLine1 => ColumnType::String(StringLen::N(255u32)).def(),
            Self::AddressLine2 => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::City => ColumnType::String(StringLen::N(100u32)).def(),
            Self::State => ColumnType::String(StringLen::N(100u32)).def(),
            Self::PostalCode => ColumnType::String(StringLen::N(20u32)).def(),
            Self::Country => ColumnType::String(StringLen::N(3u32)).def(),
            Self::AddressType => LmsAddressType::db_type().get_column_type().to_owned().def(),
            Self::IsValidated => ColumnType::Boolean.def(),
            Self::Latitude => ColumnType::Decimal(Some((10u32, 8u32))).def().null(),
            Self::Longitude => ColumnType::Decimal(Some((11u32, 8u32))).def().null(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CrmCompanies => Entity::has_many(super::crm_companies::Entity).into(),
            Self::CrmContacts => Entity::has_many(super::crm_contacts::Entity).into(),
            Self::LmsTransportationProviders => {
                Entity::has_many(super::lms_transportation_providers::Entity).into()
            }
            Self::LmsWarehouses => Entity::has_many(super::lms_warehouses::Entity).into(),
        }
    }
}

impl Related<super::crm_companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmCompanies.def()
    }
}

impl Related<super::crm_contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrmContacts.def()
    }
}

impl Related<super::lms_transportation_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsTransportationProviders.def()
    }
}

impl Related<super::lms_warehouses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsWarehouses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
