//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::LmsServiceType;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "lms_shipping_services"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub service_type: LmsServiceType,
    pub max_weight: Option<Decimal>,
    pub delivery_time_min: Option<i32>,
    pub delivery_time_max: Option<i32>,
    pub is_active: bool,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Description,
    ServiceType,
    MaxWeight,
    DeliveryTimeMin,
    DeliveryTimeMax,
    IsActive,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    LmsPricingRates,
    LmsShipments,
    LmsShippingServiceMaxDimensions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(100u32)).def().unique(),
            Self::Description => ColumnType::Text.def().null(),
            Self::ServiceType => LmsServiceType::db_type().get_column_type().to_owned().def(),
            Self::MaxWeight => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::DeliveryTimeMin => ColumnType::Integer.def().null(),
            Self::DeliveryTimeMax => ColumnType::Integer.def().null(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::LmsPricingRates => Entity::has_many(super::lms_pricing_rates::Entity).into(),
            Self::LmsShipments => Entity::has_many(super::lms_shipments::Entity).into(),
            Self::LmsShippingServiceMaxDimensions => {
                Entity::has_many(super::lms_shipping_service_max_dimensions::Entity).into()
            }
        }
    }
}

impl Related<super::lms_pricing_rates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsPricingRates.def()
    }
}

impl Related<super::lms_shipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsShipments.def()
    }
}

impl Related<super::lms_shipping_service_max_dimensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsShippingServiceMaxDimensions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
