//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::OrgVehicleStatus;
use super::sea_orm_active_enums::OrgVehicleType;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "org_vehicles"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Deserialize,
    async_graphql :: SimpleObject,
)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub vehicle_number: String,
    pub license_plate: String,
    pub vehicle_type: OrgVehicleType,
    pub make: String,
    pub model: String,
    pub year: i32,
    pub capacity_weight: Option<Decimal>,
    pub capacity_volume: Option<Decimal>,
    pub department_id: Option<Uuid>,
    pub warehouse_id: Option<Uuid>,
    pub status: OrgVehicleStatus,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq, Eq, async_graphql::Enum)]
pub enum Column {
    Id,
    VehicleNumber,
    LicensePlate,
    VehicleType,
    Make,
    Model,
    Year,
    CapacityWeight,
    CapacityVolume,
    DepartmentId,
    WarehouseId,
    Status,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    LmsRoutes,
    LmsTransportLegs,
    LmsWarehouses,
    OrgDepartments,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::VehicleNumber => ColumnType::String(StringLen::N(20u32)).def().unique(),
            Self::LicensePlate => ColumnType::String(StringLen::N(15u32)).def().unique(),
            Self::VehicleType => OrgVehicleType::db_type().get_column_type().to_owned().def(),
            Self::Make => ColumnType::String(StringLen::N(30u32)).def(),
            Self::Model => ColumnType::String(StringLen::N(30u32)).def(),
            Self::Year => ColumnType::Integer.def(),
            Self::CapacityWeight => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::CapacityVolume => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::DepartmentId => ColumnType::Uuid.def().null(),
            Self::WarehouseId => ColumnType::Uuid.def().null(),
            Self::Status => OrgVehicleStatus::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::Created => ColumnType::TimestampWithTimeZone.def(),
            Self::Updated => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::LmsRoutes => Entity::has_many(super::lms_routes::Entity).into(),
            Self::LmsTransportLegs => Entity::has_many(super::lms_transport_legs::Entity).into(),
            Self::LmsWarehouses => Entity::belongs_to(super::lms_warehouses::Entity)
                .from(Column::WarehouseId)
                .to(super::lms_warehouses::Column::Id)
                .into(),
            Self::OrgDepartments => Entity::belongs_to(super::org_departments::Entity)
                .from(Column::DepartmentId)
                .to(super::org_departments::Column::Id)
                .into(),
        }
    }
}

impl Related<super::lms_routes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsRoutes.def()
    }
}

impl Related<super::lms_transport_legs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsTransportLegs.def()
    }
}

impl Related<super::lms_warehouses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LmsWarehouses.def()
    }
}

impl Related<super::org_departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgDepartments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
