//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "case_priority")]
pub enum CasePriority {
    #[sea_orm(string_value = "critical")]
    Critical,
    #[sea_orm(string_value = "high")]
    High,
    #[sea_orm(string_value = "medium")]
    Medium,
    #[sea_orm(string_value = "low")]
    Low,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "case_status")]
pub enum CaseStatus {
    #[sea_orm(string_value = "new")]
    New,
    #[sea_orm(string_value = "in-progress")]
    InProgress,
    #[sea_orm(string_value = "waiting-for-customer")]
    WaitingForCustomer,
    #[sea_orm(string_value = "waiting-for-internal")]
    WaitingForInternal,
    #[sea_orm(string_value = "escalated")]
    Escalated,
    #[sea_orm(string_value = "resolved")]
    Resolved,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "case_type")]
pub enum CaseType {
    #[sea_orm(string_value = "question")]
    Question,
    #[sea_orm(string_value = "problem")]
    Problem,
    #[sea_orm(string_value = "complaint")]
    Complaint,
    #[sea_orm(string_value = "feature-request")]
    FeatureRequest,
    #[sea_orm(string_value = "bug-report")]
    BugReport,
    #[sea_orm(string_value = "technical-support")]
    TechnicalSupport,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "interaction_type")]
pub enum InteractionType {
    #[sea_orm(string_value = "call")]
    Call,
    #[sea_orm(string_value = "meeting")]
    Meeting,
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "email")]
    Email,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "invoice_status")]
pub enum InvoiceStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "sent")]
    Sent,
    #[sea_orm(string_value = "paid")]
    Paid,
    #[sea_orm(string_value = "overdue")]
    Overdue,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "lead_source")]
pub enum LeadSource {
    #[sea_orm(string_value = "website")]
    Website,
    #[sea_orm(string_value = "referral")]
    Referral,
    #[sea_orm(string_value = "social-media")]
    SocialMedia,
    #[sea_orm(string_value = "email-campaign")]
    EmailCampaign,
    #[sea_orm(string_value = "cold-call")]
    ColdCall,
    #[sea_orm(string_value = "event")]
    Event,
    #[sea_orm(string_value = "advertisement")]
    Advertisement,
    #[sea_orm(string_value = "partner")]
    Partner,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "lead_status")]
pub enum LeadStatus {
    #[sea_orm(string_value = "new")]
    New,
    #[sea_orm(string_value = "contacted")]
    Contacted,
    #[sea_orm(string_value = "qualified")]
    Qualified,
    #[sea_orm(string_value = "unqualified")]
    Unqualified,
    #[sea_orm(string_value = "converted")]
    Converted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "opportunity_source")]
pub enum OpportunitySource {
    #[sea_orm(string_value = "website")]
    Website,
    #[sea_orm(string_value = "referral")]
    Referral,
    #[sea_orm(string_value = "social-media")]
    SocialMedia,
    #[sea_orm(string_value = "email-campaign")]
    EmailCampaign,
    #[sea_orm(string_value = "cold-call")]
    ColdCall,
    #[sea_orm(string_value = "event")]
    Event,
    #[sea_orm(string_value = "advertisement")]
    Advertisement,
    #[sea_orm(string_value = "partner")]
    Partner,
    #[sea_orm(string_value = "existing-customer")]
    ExistingCustomer,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "opportunity_stage")]
pub enum OpportunityStage {
    #[sea_orm(string_value = "prospecting")]
    Prospecting,
    #[sea_orm(string_value = "qualification")]
    Qualification,
    #[sea_orm(string_value = "need-analysis")]
    NeedAnalysis,
    #[sea_orm(string_value = "demo")]
    Demo,
    #[sea_orm(string_value = "proposal")]
    Proposal,
    #[sea_orm(string_value = "negotiation")]
    Negotiation,
    #[sea_orm(string_value = "closed-won")]
    ClosedWon,
    #[sea_orm(string_value = "closed-lost")]
    ClosedLost,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "payment_method")]
pub enum PaymentMethod {
    #[sea_orm(string_value = "credit-card")]
    CreditCard,
    #[sea_orm(string_value = "bank-transfer")]
    BankTransfer,
    #[sea_orm(string_value = "cash")]
    Cash,
    #[sea_orm(string_value = "check")]
    Check,
    #[sea_orm(string_value = "paypal")]
    Paypal,
    #[sea_orm(string_value = "stripe")]
    Stripe,
    #[sea_orm(string_value = "wire-transfer")]
    WireTransfer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "product_type")]
pub enum ProductType {
    #[sea_orm(string_value = "service")]
    Service,
    #[sea_orm(string_value = "good")]
    Good,
    #[sea_orm(string_value = "digital")]
    Digital,
    #[sea_orm(string_value = "subscription")]
    Subscription,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, async_graphql :: Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "record_type")]
pub enum RecordType {
    #[sea_orm(string_value = "companies")]
    Companies,
    #[sea_orm(string_value = "contacts")]
    Contacts,
    #[sea_orm(string_value = "leads")]
    Leads,
    #[sea_orm(string_value = "opportunities")]
    Opportunities,
    #[sea_orm(string_value = "cases")]
    Cases,
    #[sea_orm(string_value = "interactions")]
    Interactions,
    #[sea_orm(string_value = "campaigns")]
    Campaigns,
    #[sea_orm(string_value = "products")]
    Products,
    #[sea_orm(string_value = "invoices")]
    Invoices,
}
