// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
insert into products (
  sku, 
  name, 
  description, 
  width, 
  height, 
  length, 
  cost, 
  supplier, 
  image_url
)
values (
  $1::text, 
  $2::text, 
  $3::text, 
  $4::numeric, 
  $5::numeric, 
  $6::numeric, 
  $7::numeric, 
  $8::uuid, 
  $9::text
)
returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type CreateProductParams struct {
	Sku         string
	Name        string
	Description string
	Width       pgtype.Numeric
	Height      pgtype.Numeric
	Length      pgtype.Numeric
	Cost        pgtype.Numeric
	Supplier    pgtype.UUID
	ImageUrl    string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Width,
		arg.Height,
		arg.Length,
		arg.Cost,
		arg.Supplier,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
delete from products where id = $1::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getAllProducts = `-- name: GetAllProducts :many
select id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated from products order by created desc
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Width,
			&i.Height,
			&i.Length,
			&i.Cost,
			&i.Supplier,
			&i.ImageUrl,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
select id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated from products where id = $1::uuid
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductsBySupplier = `-- name: GetProductsBySupplier :many
select id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated from products where supplier = $1::uuid order by created desc offset $2::integer limit $3::integer
`

type GetProductsBySupplierParams struct {
	Supplier pgtype.UUID
	Page     int32
	PerPage  int32
}

func (q *Queries) GetProductsBySupplier(ctx context.Context, arg GetProductsBySupplierParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsBySupplier, arg.Supplier, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Width,
			&i.Height,
			&i.Length,
			&i.Cost,
			&i.Supplier,
			&i.ImageUrl,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateProducts = `-- name: PaginateProducts :many
select id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated from products order by created desc offset $1::integer limit $2::integer
`

type PaginateProductsParams struct {
	Page    int32
	PerPage int32
}

func (q *Queries) PaginateProducts(ctx context.Context, arg PaginateProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, paginateProducts, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Width,
			&i.Height,
			&i.Length,
			&i.Cost,
			&i.Supplier,
			&i.ImageUrl,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
select id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated from products where name ilike '%' || $1::text || '%' or description ilike '%' || $1::text || '%' or sku ilike '%' || $1::text || '%' order by created desc offset $2::integer limit $3::integer
`

type SearchProductsParams struct {
	SearchText string
	Page       int32
	PerPage    int32
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.SearchText, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Width,
			&i.Height,
			&i.Length,
			&i.Cost,
			&i.Supplier,
			&i.ImageUrl,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductCost = `-- name: UpdateProductCost :one
update products set cost = $1::numeric where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductCostParams struct {
	Cost pgtype.Numeric
	ID   pgtype.UUID
}

func (q *Queries) UpdateProductCost(ctx context.Context, arg UpdateProductCostParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductCost, arg.Cost, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductDescription = `-- name: UpdateProductDescription :one
update products set description = $1::text where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductDescriptionParams struct {
	Description string
	ID          pgtype.UUID
}

func (q *Queries) UpdateProductDescription(ctx context.Context, arg UpdateProductDescriptionParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductDescription, arg.Description, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductHeight = `-- name: UpdateProductHeight :one
update products set height = $1::numeric where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductHeightParams struct {
	Height pgtype.Numeric
	ID     pgtype.UUID
}

func (q *Queries) UpdateProductHeight(ctx context.Context, arg UpdateProductHeightParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductHeight, arg.Height, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductImageURL = `-- name: UpdateProductImageURL :one
update products set image_url = $1::text where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductImageURLParams struct {
	ImageUrl string
	ID       pgtype.UUID
}

func (q *Queries) UpdateProductImageURL(ctx context.Context, arg UpdateProductImageURLParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductImageURL, arg.ImageUrl, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductLength = `-- name: UpdateProductLength :one
update products set length = $1::numeric where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductLengthParams struct {
	Length pgtype.Numeric
	ID     pgtype.UUID
}

func (q *Queries) UpdateProductLength(ctx context.Context, arg UpdateProductLengthParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductLength, arg.Length, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductName = `-- name: UpdateProductName :one
update products set name = $1::text where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductNameParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateProductName(ctx context.Context, arg UpdateProductNameParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductName, arg.Name, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductSupplier = `-- name: UpdateProductSupplier :one
update products set supplier = $1::uuid where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductSupplierParams struct {
	Supplier pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) UpdateProductSupplier(ctx context.Context, arg UpdateProductSupplierParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductSupplier, arg.Supplier, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateProductWidth = `-- name: UpdateProductWidth :one
update products set width = $1::numeric where id = $2::uuid returning id, sku, name, description, width, height, length, cost, supplier, image_url, created, updated
`

type UpdateProductWidthParams struct {
	Width pgtype.Numeric
	ID    pgtype.UUID
}

func (q *Queries) UpdateProductWidth(ctx context.Context, arg UpdateProductWidthParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductWidth, arg.Width, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Width,
		&i.Height,
		&i.Length,
		&i.Cost,
		&i.Supplier,
		&i.ImageUrl,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
