//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::PartnerInvoiceStatusEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "tms", table_name = "partner_invoices")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub carrier_id: Uuid,
    pub invoice_number: String,
    pub invoice_date: Date,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub total_amount: Decimal,
    pub status: Option<PartnerInvoiceStatusEnum>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::carriers::Entity",
        from = "Column::CarrierId",
        to = "super::carriers::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Carriers,
    #[sea_orm(has_many = "super::partner_invoice_items::Entity")]
    PartnerInvoiceItems,
}

impl Related<super::carriers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Carriers.def()
    }
}

impl Related<super::partner_invoice_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartnerInvoiceItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
