//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "tms", table_name = "routes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub trip_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub optimized_route_data: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub total_distance: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub total_duration: Option<f32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::trips::Entity",
        from = "Column::TripId",
        to = "super::trips::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Trips,
}

impl Related<super::trips::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trips.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
