//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "tms", table_name = "shipment_leg_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub shipment_leg_id: Uuid,
    pub status_message: Option<String>,
    pub location: Option<String>,
    pub event_timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::shipment_legs::Entity",
        from = "Column::ShipmentLegId",
        to = "super::shipment_legs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShipmentLegs,
}

impl Related<super::shipment_legs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShipmentLegs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
