//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, ts_rs :: TS)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "table_permission_enum"
)]
#[ts(export_to = "./rust-bindings.ts")]
#[serde(rename_all = "camelCase")]
pub enum TablePermissionEnum {
    #[sea_orm(string_value = "read")]
    Read,
    #[sea_orm(string_value = "write")]
    Write,
    #[sea_orm(string_value = "update")]
    Update,
    #[sea_orm(string_value = "delete")]
    Delete,
}
