/**
 * Auto-generated Zod schema for CustomerRelationsCases
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import * as PB from "../../../lib/pb.types";

export const CasesSchema = z.object({
  caseNumber: z.string(),
  contact: z.string().optional(),
  created: z.iso.date(),
  description: z.string().optional(),
  id: z.string(),
  owner: z.string(),
  priority: z.enum(PB.CustomerRelationsCasesPriorityOptions),
  status: z.enum(PB.CustomerRelationsCasesStatusOptions),
  type: z.enum(PB.CustomerRelationsCasesTypeOptions),
  updated: z.iso.date(),
});

export type Cases = z.infer<typeof CasesSchema>;
