/**
 * Auto-generated Zod schema for CustomerRelationsOpportunities
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import * as PB from "../../../lib/pb.types";

export const OpportunitiesSchema = z.object({
  attachments: z.array(z.string()).optional(),
  campaign: z.string().optional(),
  company: z.string().optional(),
  contact: z.string().optional(),
  created: z.iso.date(),
  dealValue: z.number().optional(),
  expectedCloseDate: z.iso.date().optional(),
  id: z.string(),
  lostReason: z.string().optional(),
  name: z.string(),
  owner: z.string(),
  probability: z.number().optional(),
  products: z.array(z.string()).optional(),
  source: z.enum(PB.CustomerRelationsOpportunitiesSourceOptions),
  stage: z.enum(PB.CustomerRelationsOpportunitiesStageOptions).optional(),
  updated: z.iso.date(),
});

export type Opportunities = z.infer<typeof OpportunitiesSchema>;
