services:
  logistics-management-system:
    image: registry.marahuyo.dev/logistics-management-system:latest
    environment:
      - PUBLIC_DOMAIN_NAME=f-org-e.systems
      - PUBLIC_BACKEND_URL=https://f-org-e.systems
    networks:
      - marahuyo.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.logistics-management-system.loadbalancer.server.port=80"
      - "traefik.http.routers.logistics-management-system.rule=Host(`api.f-org-e.systems`) || Host(`www.f-org-e.systems`) || Host(`f-org-e.systems`)"
      - "traefik.http.routers.logistics-management-system.entrypoints=web-secure"
      - "traefik.http.routers.logistics-management-system.tls=true"
      - "traefik.http.routers.logistics-management-system.tls.certresolver=cloudflare"
    volumes:
      - logistics-management-system-data:/app/pb_data 

volumes:
  logistics-management-system-data:
networks:
  marahuyo.dev:
    external: true