services:
  logistics-management-system:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - "8090:80"
    volumes:
      - logistics-management-system-data:/app/pb_data

volumes:
  logistics-management-system-data: