/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as LoginImport } from './routes/login'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardWarehousesIndexImport } from './routes/dashboard/warehouses/index'
import { Route as DashboardTasksIndexImport } from './routes/dashboard/tasks/index'
import { Route as DashboardShipmentsIndexImport } from './routes/dashboard/shipments/index'
import { Route as DashboardProfileIndexImport } from './routes/dashboard/profile/index'
import { Route as DashboardProductsIndexImport } from './routes/dashboard/products/index'
import { Route as DashboardOrdersIndexImport } from './routes/dashboard/orders/index'
import { Route as DashboardInventoryIndexImport } from './routes/dashboard/inventory/index'
import { Route as DashboardDepartmentsIndexImport } from './routes/dashboard/departments/index'
import { Route as DashboardCompaniesIndexImport } from './routes/dashboard/companies/index'
import { Route as DashboardChatIndexImport } from './routes/dashboard/chat/index'
import { Route as DashboardCollectionIndexImport } from './routes/dashboard/$collection/index'
import { Route as DashboardTasksMyTasksImport } from './routes/dashboard/tasks/my-tasks'
import { Route as DashboardChatNewImport } from './routes/dashboard/chat/new'
import { Route as DashboardChatRoomidImport } from './routes/dashboard/chat/$room_id'
import { Route as DashboardUsersUseridIndexImport } from './routes/dashboard/users/$user_id/index'
import { Route as DashboardUsersUseridEditImport } from './routes/dashboard/users/$user_id/edit'
import { Route as DashboardTasksDepartmentDepartmentidIndexImport } from './routes/dashboard/tasks/department/$department_id/index'
import { Route as DashboardChatStartSupportCustomeridImport } from './routes/dashboard/chat/start/support/$customer_id'
import { Route as DashboardChatStartOrderOrderidImport } from './routes/dashboard/chat/start/order/$order_id'

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardWarehousesIndexRoute = DashboardWarehousesIndexImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTasksIndexRoute = DashboardTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardShipmentsIndexRoute = DashboardShipmentsIndexImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProfileIndexRoute = DashboardProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProductsIndexRoute = DashboardProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOrdersIndexRoute = DashboardOrdersIndexImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardInventoryIndexRoute = DashboardInventoryIndexImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDepartmentsIndexRoute = DashboardDepartmentsIndexImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardCompaniesIndexRoute = DashboardCompaniesIndexImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardChatIndexRoute = DashboardChatIndexImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardCollectionIndexRoute = DashboardCollectionIndexImport.update({
  id: '/$collection/',
  path: '/$collection/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTasksMyTasksRoute = DashboardTasksMyTasksImport.update({
  id: '/tasks/my-tasks',
  path: '/tasks/my-tasks',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardChatNewRoute = DashboardChatNewImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardChatRoomidRoute = DashboardChatRoomidImport.update({
  id: '/chat/$room_id',
  path: '/chat/$room_id',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersUseridIndexRoute = DashboardUsersUseridIndexImport.update({
  id: '/users/$user_id/',
  path: '/users/$user_id/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersUseridEditRoute = DashboardUsersUseridEditImport.update({
  id: '/users/$user_id/edit',
  path: '/users/$user_id/edit',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTasksDepartmentDepartmentidIndexRoute =
  DashboardTasksDepartmentDepartmentidIndexImport.update({
    id: '/tasks/department/$department_id/',
    path: '/tasks/department/$department_id/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardChatStartSupportCustomeridRoute =
  DashboardChatStartSupportCustomeridImport.update({
    id: '/chat/start/support/$customer_id',
    path: '/chat/start/support/$customer_id',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardChatStartOrderOrderidRoute =
  DashboardChatStartOrderOrderidImport.update({
    id: '/chat/start/order/$order_id',
    path: '/chat/start/order/$order_id',
    getParentRoute: () => DashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/chat/$room_id': {
      id: '/dashboard/chat/$room_id'
      path: '/chat/$room_id'
      fullPath: '/dashboard/chat/$room_id'
      preLoaderRoute: typeof DashboardChatRoomidImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/chat/new': {
      id: '/dashboard/chat/new'
      path: '/chat/new'
      fullPath: '/dashboard/chat/new'
      preLoaderRoute: typeof DashboardChatNewImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/tasks/my-tasks': {
      id: '/dashboard/tasks/my-tasks'
      path: '/tasks/my-tasks'
      fullPath: '/dashboard/tasks/my-tasks'
      preLoaderRoute: typeof DashboardTasksMyTasksImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/$collection/': {
      id: '/dashboard/$collection/'
      path: '/$collection'
      fullPath: '/dashboard/$collection'
      preLoaderRoute: typeof DashboardCollectionIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/chat/': {
      id: '/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/companies/': {
      id: '/dashboard/companies/'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof DashboardCompaniesIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/departments/': {
      id: '/dashboard/departments/'
      path: '/departments'
      fullPath: '/dashboard/departments'
      preLoaderRoute: typeof DashboardDepartmentsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/shipments/': {
      id: '/dashboard/shipments/'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof DashboardShipmentsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/warehouses/': {
      id: '/dashboard/warehouses/'
      path: '/warehouses'
      fullPath: '/dashboard/warehouses'
      preLoaderRoute: typeof DashboardWarehousesIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/users/$user_id/edit': {
      id: '/dashboard/users/$user_id/edit'
      path: '/users/$user_id/edit'
      fullPath: '/dashboard/users/$user_id/edit'
      preLoaderRoute: typeof DashboardUsersUseridEditImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/users/$user_id/': {
      id: '/dashboard/users/$user_id/'
      path: '/users/$user_id'
      fullPath: '/dashboard/users/$user_id'
      preLoaderRoute: typeof DashboardUsersUseridIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/chat/start/order/$order_id': {
      id: '/dashboard/chat/start/order/$order_id'
      path: '/chat/start/order/$order_id'
      fullPath: '/dashboard/chat/start/order/$order_id'
      preLoaderRoute: typeof DashboardChatStartOrderOrderidImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/chat/start/support/$customer_id': {
      id: '/dashboard/chat/start/support/$customer_id'
      path: '/chat/start/support/$customer_id'
      fullPath: '/dashboard/chat/start/support/$customer_id'
      preLoaderRoute: typeof DashboardChatStartSupportCustomeridImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/tasks/department/$department_id/': {
      id: '/dashboard/tasks/department/$department_id/'
      path: '/tasks/department/$department_id'
      fullPath: '/dashboard/tasks/department/$department_id'
      preLoaderRoute: typeof DashboardTasksDepartmentDepartmentidIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChatRoomidRoute: typeof DashboardChatRoomidRoute
  DashboardChatNewRoute: typeof DashboardChatNewRoute
  DashboardTasksMyTasksRoute: typeof DashboardTasksMyTasksRoute
  DashboardCollectionIndexRoute: typeof DashboardCollectionIndexRoute
  DashboardChatIndexRoute: typeof DashboardChatIndexRoute
  DashboardCompaniesIndexRoute: typeof DashboardCompaniesIndexRoute
  DashboardDepartmentsIndexRoute: typeof DashboardDepartmentsIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardShipmentsIndexRoute: typeof DashboardShipmentsIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
  DashboardWarehousesIndexRoute: typeof DashboardWarehousesIndexRoute
  DashboardUsersUseridEditRoute: typeof DashboardUsersUseridEditRoute
  DashboardUsersUseridIndexRoute: typeof DashboardUsersUseridIndexRoute
  DashboardChatStartOrderOrderidRoute: typeof DashboardChatStartOrderOrderidRoute
  DashboardChatStartSupportCustomeridRoute: typeof DashboardChatStartSupportCustomeridRoute
  DashboardTasksDepartmentDepartmentidIndexRoute: typeof DashboardTasksDepartmentDepartmentidIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChatRoomidRoute: DashboardChatRoomidRoute,
  DashboardChatNewRoute: DashboardChatNewRoute,
  DashboardTasksMyTasksRoute: DashboardTasksMyTasksRoute,
  DashboardCollectionIndexRoute: DashboardCollectionIndexRoute,
  DashboardChatIndexRoute: DashboardChatIndexRoute,
  DashboardCompaniesIndexRoute: DashboardCompaniesIndexRoute,
  DashboardDepartmentsIndexRoute: DashboardDepartmentsIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardShipmentsIndexRoute: DashboardShipmentsIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
  DashboardWarehousesIndexRoute: DashboardWarehousesIndexRoute,
  DashboardUsersUseridEditRoute: DashboardUsersUseridEditRoute,
  DashboardUsersUseridIndexRoute: DashboardUsersUseridIndexRoute,
  DashboardChatStartOrderOrderidRoute: DashboardChatStartOrderOrderidRoute,
  DashboardChatStartSupportCustomeridRoute:
    DashboardChatStartSupportCustomeridRoute,
  DashboardTasksDepartmentDepartmentidIndexRoute:
    DashboardTasksDepartmentDepartmentidIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/chat/$room_id': typeof DashboardChatRoomidRoute
  '/dashboard/chat/new': typeof DashboardChatNewRoute
  '/dashboard/tasks/my-tasks': typeof DashboardTasksMyTasksRoute
  '/dashboard/$collection': typeof DashboardCollectionIndexRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/companies': typeof DashboardCompaniesIndexRoute
  '/dashboard/departments': typeof DashboardDepartmentsIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/shipments': typeof DashboardShipmentsIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/warehouses': typeof DashboardWarehousesIndexRoute
  '/dashboard/users/$user_id/edit': typeof DashboardUsersUseridEditRoute
  '/dashboard/users/$user_id': typeof DashboardUsersUseridIndexRoute
  '/dashboard/chat/start/order/$order_id': typeof DashboardChatStartOrderOrderidRoute
  '/dashboard/chat/start/support/$customer_id': typeof DashboardChatStartSupportCustomeridRoute
  '/dashboard/tasks/department/$department_id': typeof DashboardTasksDepartmentDepartmentidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/chat/$room_id': typeof DashboardChatRoomidRoute
  '/dashboard/chat/new': typeof DashboardChatNewRoute
  '/dashboard/tasks/my-tasks': typeof DashboardTasksMyTasksRoute
  '/dashboard/$collection': typeof DashboardCollectionIndexRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/companies': typeof DashboardCompaniesIndexRoute
  '/dashboard/departments': typeof DashboardDepartmentsIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/shipments': typeof DashboardShipmentsIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/warehouses': typeof DashboardWarehousesIndexRoute
  '/dashboard/users/$user_id/edit': typeof DashboardUsersUseridEditRoute
  '/dashboard/users/$user_id': typeof DashboardUsersUseridIndexRoute
  '/dashboard/chat/start/order/$order_id': typeof DashboardChatStartOrderOrderidRoute
  '/dashboard/chat/start/support/$customer_id': typeof DashboardChatStartSupportCustomeridRoute
  '/dashboard/tasks/department/$department_id': typeof DashboardTasksDepartmentDepartmentidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/chat/$room_id': typeof DashboardChatRoomidRoute
  '/dashboard/chat/new': typeof DashboardChatNewRoute
  '/dashboard/tasks/my-tasks': typeof DashboardTasksMyTasksRoute
  '/dashboard/$collection/': typeof DashboardCollectionIndexRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/companies/': typeof DashboardCompaniesIndexRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/shipments/': typeof DashboardShipmentsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/dashboard/warehouses/': typeof DashboardWarehousesIndexRoute
  '/dashboard/users/$user_id/edit': typeof DashboardUsersUseridEditRoute
  '/dashboard/users/$user_id/': typeof DashboardUsersUseridIndexRoute
  '/dashboard/chat/start/order/$order_id': typeof DashboardChatStartOrderOrderidRoute
  '/dashboard/chat/start/support/$customer_id': typeof DashboardChatStartSupportCustomeridRoute
  '/dashboard/tasks/department/$department_id/': typeof DashboardTasksDepartmentDepartmentidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/'
    | '/dashboard/chat/$room_id'
    | '/dashboard/chat/new'
    | '/dashboard/tasks/my-tasks'
    | '/dashboard/$collection'
    | '/dashboard/chat'
    | '/dashboard/companies'
    | '/dashboard/departments'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/shipments'
    | '/dashboard/tasks'
    | '/dashboard/warehouses'
    | '/dashboard/users/$user_id/edit'
    | '/dashboard/users/$user_id'
    | '/dashboard/chat/start/order/$order_id'
    | '/dashboard/chat/start/support/$customer_id'
    | '/dashboard/tasks/department/$department_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/dashboard/chat/$room_id'
    | '/dashboard/chat/new'
    | '/dashboard/tasks/my-tasks'
    | '/dashboard/$collection'
    | '/dashboard/chat'
    | '/dashboard/companies'
    | '/dashboard/departments'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/shipments'
    | '/dashboard/tasks'
    | '/dashboard/warehouses'
    | '/dashboard/users/$user_id/edit'
    | '/dashboard/users/$user_id'
    | '/dashboard/chat/start/order/$order_id'
    | '/dashboard/chat/start/support/$customer_id'
    | '/dashboard/tasks/department/$department_id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/'
    | '/dashboard/chat/$room_id'
    | '/dashboard/chat/new'
    | '/dashboard/tasks/my-tasks'
    | '/dashboard/$collection/'
    | '/dashboard/chat/'
    | '/dashboard/companies/'
    | '/dashboard/departments/'
    | '/dashboard/inventory/'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/profile/'
    | '/dashboard/shipments/'
    | '/dashboard/tasks/'
    | '/dashboard/warehouses/'
    | '/dashboard/users/$user_id/edit'
    | '/dashboard/users/$user_id/'
    | '/dashboard/chat/start/order/$order_id'
    | '/dashboard/chat/start/support/$customer_id'
    | '/dashboard/tasks/department/$department_id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/forgot-password",
        "/login",
        "/reset-password"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/",
        "/dashboard/chat/$room_id",
        "/dashboard/chat/new",
        "/dashboard/tasks/my-tasks",
        "/dashboard/$collection/",
        "/dashboard/chat/",
        "/dashboard/companies/",
        "/dashboard/departments/",
        "/dashboard/inventory/",
        "/dashboard/orders/",
        "/dashboard/products/",
        "/dashboard/profile/",
        "/dashboard/shipments/",
        "/dashboard/tasks/",
        "/dashboard/warehouses/",
        "/dashboard/users/$user_id/edit",
        "/dashboard/users/$user_id/",
        "/dashboard/chat/start/order/$order_id",
        "/dashboard/chat/start/support/$customer_id",
        "/dashboard/tasks/department/$department_id/"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/chat/$room_id": {
      "filePath": "dashboard/chat/$room_id.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/chat/new": {
      "filePath": "dashboard/chat/new.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/tasks/my-tasks": {
      "filePath": "dashboard/tasks/my-tasks.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/$collection/": {
      "filePath": "dashboard/$collection/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/chat/": {
      "filePath": "dashboard/chat/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/companies/": {
      "filePath": "dashboard/companies/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/departments/": {
      "filePath": "dashboard/departments/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/inventory/": {
      "filePath": "dashboard/inventory/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/orders/": {
      "filePath": "dashboard/orders/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/products/": {
      "filePath": "dashboard/products/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/profile/": {
      "filePath": "dashboard/profile/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/shipments/": {
      "filePath": "dashboard/shipments/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/tasks/": {
      "filePath": "dashboard/tasks/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/warehouses/": {
      "filePath": "dashboard/warehouses/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/users/$user_id/edit": {
      "filePath": "dashboard/users/$user_id/edit.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/users/$user_id/": {
      "filePath": "dashboard/users/$user_id/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/chat/start/order/$order_id": {
      "filePath": "dashboard/chat/start/order/$order_id.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/chat/start/support/$customer_id": {
      "filePath": "dashboard/chat/start/support/$customer_id.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/tasks/department/$department_id/": {
      "filePath": "dashboard/tasks/department/$department_id/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
