/**
 * Auto-generated Zod schema for WarehouseManagementPickBatches
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import * as PB from "../../../lib/pb.types";

export const PickBatchesSchema = z.object({
  actualDuration: z.number().optional(),
  assignedUser: z.string().optional(),
  batchNumber: z.string().optional(),
  completedAt: z.iso.date().optional(),
  completedItems: z.number().optional(),
  created: z.iso.date(),
  estimatedDuration: z.number().optional(),
  id: z.string(),
  items: z.array(z.string()).optional(),
  priority: z.number(),
  startedAt: z.iso.date().optional(),
  status: z.enum(PB.WarehouseManagementPickBatchesStatusOptions).optional(),
  strategy: z.enum(PB.WarehouseManagementPickBatchesStrategyOptions).optional(),
  totalItems: z.number().optional(),
  updated: z.iso.date(),
  warehouse: z.string().optional(),
});

export type PickBatches = z.infer<typeof PickBatchesSchema>;
