/**
 * Auto-generated Zod schema for WarehouseManagementTasks
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import * as PB from "../../../lib/pb.types";

export const TasksSchema = z.object({
  attachments: z.array(z.string()).optional(),
  created: z.iso.date(),
  endTime: z.iso.date().optional(),
  id: z.string(),
  instructions: z.string().optional(),
  notes: z.string().optional(),
  pickBatchId: z.string().optional(),
  priority: z.number(),
  startTime: z.iso.date().optional(),
  status: z.enum(PB.WarehouseManagementTasksStatusOptions).optional(),
  taskNumber: z.string(),
  type: z.enum(PB.WarehouseManagementTasksTypeOptions).optional(),
  updated: z.iso.date(),
  user: z.string().optional(),
  warehouse: z.string().optional(),
});

export type Tasks = z.infer<typeof TasksSchema>;
