/**
 * Auto-generated Zod schema for TransportManagementCarriers
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";

export const CarriersSchema = z.object({
  id: z.string(),
  name: z.string(),
  contactDetails: z.unknown().optional(),
  serviceOffered: z.unknown().optional(),
  image: z.string().optional(),
  created: z.iso.datetime().optional(),
  updated: z.iso.datetime().optional(),
});

export type Carriers = z.infer<typeof CarriersSchema>;
