/**
 * Auto-generated Zod schema for TransportManagementDriverSchedules
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import * as PB from "../../../lib/pb.types";

export const DriverSchedulesSchema = z.object({
  created: z.iso.date(),
  driver: z.string(),
  endDate: z.iso.date(),
  id: z.string(),
  reason: z.enum(PB.TransportManagementDriverSchedulesReasonOptions).optional(),
  startDate: z.iso.date(),
  updated: z.iso.date(),
});

export type DriverSchedules = z.infer<typeof DriverSchedulesSchema>;
