/**
 * Auto-generated Zod schema for TransportManagementExpenses
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import {
  fieldRegistry,
  fieldSetRegistry,
} from "@/components/ui/autoform-tanstack/types";
import { RelationFieldProps } from "@/components/ui/forms/fields";
import { Collections } from "@/lib/pb.types";

export const ExpensesSchema = z
  .object({
    id: z.string().register(fieldRegistry, {
      id: "id",
      type: "field",
      inputType: "text",
      label: "Expense ID",
      description: "Unique identifier for the expense",
      props: {
        disabled: true,
      },
    }),
    trip: z
      .string()
      .optional()
      .register(fieldRegistry, {
        type: "field",
        id: "trip",
        inputType: "relation",
        label: "Trip",
        description: "Associated trip",
        props: {
          collectionName: Collections.TransportManagementTrips,
          relationshipName: "trip",
          displayField: "id",
        } as RelationFieldProps<any>,
      }),
    driver: z
      .string()
      .optional()
      .register(fieldRegistry, {
        type: "field",
        id: "driver",
        inputType: "relation",
        label: "Driver",
        description: "Driver who incurred the expense",
        props: {
          collectionName: Collections.TransportManagementDrivers,
          relationshipName: "driver",
          displayField: "licenseNumber",
        } as RelationFieldProps<any>,
      }),
    type: z
      .enum([
        "fuel",
        "tolls",
        "maintenance",
        "parking",
        "meals",
        "accomodation",
      ])
      .register(fieldRegistry, {
        id: "type",
        type: "field",
        inputType: "select",
        label: "Type",
        description: "Type of expense",
        props: {
          options: [
            { label: "Fuel", value: "fuel" },
            { label: "Tolls", value: "tolls" },
            { label: "Maintenance", value: "maintenance" },
            { label: "Parking", value: "parking" },
            { label: "Meals", value: "meals" },
            { label: "Accommodation", value: "accomodation" },
          ],
        },
      }),
    amount: z.number().register(fieldRegistry, {
      id: "amount",
      type: "field",
      inputType: "number",
      label: "Amount",
      description: "Expense amount",
      props: {
        placeholder: "0.00",
        min: 0,
      },
    }),
    currency: z.enum(["PHP", "USD", "EUR"]).register(fieldRegistry, {
      id: "currency",
      type: "field",
      inputType: "select",
      label: "Currency",
      description: "Currency of the amount",
      props: {
        options: [
          { label: "PHP", value: "PHP" },
          { label: "USD", value: "USD" },
          { label: "EUR", value: "EUR" },
        ],
      },
    }),
    receipts: z.array(z.file()).register(fieldRegistry, {
      id: "receipts",
      type: "field",
      inputType: "file",
      label: "Receipts",
      description: "Receipt files for this expense",
      props: {
        multiple: true,
        accept: "*/*",
      },
    }),
    fuelQuantity: z
      .number()
      .optional()
      .register(fieldRegistry, {
        id: "fuelQuantity",
        type: "field",
        inputType: "number",
        label: "Fuel Quantity",
        description: "Amount of fuel in liters",
        props: {
          placeholder: "0.00",
          min: 0,
        },
      }),
    odometerReading: z.number().register(fieldRegistry, {
      id: "odometerReading",
      type: "field",
      inputType: "number",
      label: "Odometer Reading",
      description: "Vehicle odometer reading in km",
      props: {
        placeholder: "0",
        min: 0,
      },
    }),
    status: z
      .enum(["pending", "approved", "rejected", "reimbursed"])
      .register(fieldRegistry, {
        id: "status",
        type: "field",
        inputType: "select",
        label: "Status",
        description: "Current status of the expense",
        props: {
          options: [
            { label: "Pending", value: "pending" },
            { label: "Approved", value: "approved" },
            { label: "Rejected", value: "rejected" },
            { label: "Reimbursed", value: "reimbursed" },
          ],
        },
      }),
    created: z.iso
      .datetime()
      .optional()
      .register(fieldRegistry, {
        id: "created",
        type: "field",
        inputType: "date",
        label: "Created At",
        description: "Timestamp when created",
        props: {
          disabled: true,
        },
      }),
    updated: z.iso
      .datetime()
      .optional()
      .register(fieldRegistry, {
        id: "updated",
        type: "field",
        inputType: "date",
        label: "Updated At",
        description: "Timestamp when last updated",
        props: {
          disabled: true,
        },
      }),
  })
  .register(fieldSetRegistry, { separator: true });

export type Expenses = z.infer<typeof ExpensesSchema>;
