/**
 * Auto-generated Zod schema for TransportManagementGpsPings
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import { fieldConfigFactory } from "@/components/ui/autoform/AutoForm";
import { Collections } from "@/lib/pb.types";

export const GpsPingsSchema = z.object({
	id: z.string(),
	vehicle: z.string().check(
		fieldConfigFactory<"relation">()({
			fieldType: "relation",
			customData: {
				collectionName: Collections.TransportManagementVehicles,
				displayField: "id",
			},
		}),
	),
	coordinates: z.unknown(),
	timestamp: z.iso.datetime().optional(),
});

export type GpsPings = z.infer<typeof GpsPingsSchema>;
