/**
 * Auto-generated Zod schema for TransportManagementPartnerInvoice
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";

export const PartnerInvoiceSchema = z.object({
  id: z.string(),
  carrier: z.string(),
  invoiceNumber: z.string(),
  invoiceDate: z.date(),
  totalAmount: z.number(),
  status: z
    .enum(["pending", "paid", "disputed", "overdue", "cancelled"])
    .optional(),
  items: z.string().optional(),
  created: z.iso.datetime().optional(),
  updated: z.iso.datetime().optional(),
});

export type PartnerInvoice = z.infer<typeof PartnerInvoiceSchema>;
