/**
 * Auto-generated Zod schema for TransportManagementProofOfDeliveries
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import {
  fieldRegistry,
  fieldSetRegistry,
} from "@/components/ui/autoform-tanstack/types";
import { RelationFieldProps } from "@/components/ui/forms/fields";
import { Collections } from "@/lib/pb.types";

export const ProofOfDeliveriesSchema = z.object({
  id: z.string(),
  tripStop: z.string(),
  coordinate: z.unknown(),
  attachments: z.array(z.file()).optional(),
  created: z.iso.datetime().optional(),
  updated: z.iso.datetime().optional(),
});

export type ProofOfDeliveries = z.infer<typeof ProofOfDeliveriesSchema>;
