// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: crm_campaigns.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crmAnyCampaign = `-- name: CrmAnyCampaign :many
select
  id, name, budget, start_date, end_date, created_at, updated_at
from
  "crm"."campaigns"
where
  id = any ($1::uuid[])
`

func (q *Queries) CrmAnyCampaign(ctx context.Context, ids []pgtype.UUID) ([]CrmCampaign, error) {
	rows, err := q.db.Query(ctx, crmAnyCampaign, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCampaign
	for rows.Next() {
		var i CrmCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Budget,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crmFindCampaign = `-- name: CrmFindCampaign :one
select
  id, name, budget, start_date, end_date, created_at, updated_at
from
  "crm"."campaigns"
where
  id = $1::uuid
`

func (q *Queries) CrmFindCampaign(ctx context.Context, id pgtype.UUID) (CrmCampaign, error) {
	row := q.db.QueryRow(ctx, crmFindCampaign, id)
	var i CrmCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Budget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const crmInsertCampaign = `-- name: CrmInsertCampaign :one
insert into "crm"."campaigns"(name, budget, start_date, end_date)
  values ($1, $2, $3, $4)
returning
  id, name, budget, start_date, end_date, created_at, updated_at
`

type CrmInsertCampaignParams struct {
	Name      string         `db:"name" json:"name"`
	Budget    pgtype.Numeric `db:"budget" json:"budget"`
	StartDate pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date    `db:"end_date" json:"end_date"`
}

func (q *Queries) CrmInsertCampaign(ctx context.Context, arg CrmInsertCampaignParams) (CrmCampaign, error) {
	row := q.db.QueryRow(ctx, crmInsertCampaign,
		arg.Name,
		arg.Budget,
		arg.StartDate,
		arg.EndDate,
	)
	var i CrmCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Budget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const crmPaginateCampaign = `-- name: CrmPaginateCampaign :many
select
  id, name, budget, start_date, end_date, created_at, updated_at
from
  "crm"."campaigns"
where (name ilike $1::text
  or $1::text is null)
limit $3::int offset ($2::int - 1) * $3::int
`

type CrmPaginateCampaignParams struct {
	Search  pgtype.Text `db:"search" json:"search"`
	Page    int32       `db:"page" json:"page"`
	PerPage int32       `db:"per_page" json:"per_page"`
}

func (q *Queries) CrmPaginateCampaign(ctx context.Context, arg CrmPaginateCampaignParams) ([]CrmCampaign, error) {
	rows, err := q.db.Query(ctx, crmPaginateCampaign, arg.Search, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCampaign
	for rows.Next() {
		var i CrmCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Budget,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crmRangeCampaign = `-- name: CrmRangeCampaign :many
select
  id, name, budget, start_date, end_date, created_at, updated_at
from
  "crm"."campaigns"
where
  created_at >= $1::date
  and created_at <= $2::date
  and (name ilike $3::text
    or $3::text is null)
`

type CrmRangeCampaignParams struct {
	Datefrom pgtype.Date `db:"datefrom" json:"datefrom"`
	Dateto   pgtype.Date `db:"dateto" json:"dateto"`
	Search   pgtype.Text `db:"search" json:"search"`
}

func (q *Queries) CrmRangeCampaign(ctx context.Context, arg CrmRangeCampaignParams) ([]CrmCampaign, error) {
	rows, err := q.db.Query(ctx, crmRangeCampaign, arg.Datefrom, arg.Dateto, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCampaign
	for rows.Next() {
		var i CrmCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Budget,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crmRemoveCampaign = `-- name: CrmRemoveCampaign :exec
delete from "crm"."campaigns"
where id = $1::uuid
`

func (q *Queries) CrmRemoveCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, crmRemoveCampaign, id)
	return err
}

const crmUpdateCampaign = `-- name: CrmUpdateCampaign :one
update
  "crm"."campaigns"
set
  updated_at = now(),
  name = case when $1 is not null then
    $1::text
  else
    name
  end,
  budget = case when $2 is not null then
    $2::numeric
  else
    budget
  end,
  start_date = case when $3 is not null then
    $3::date
  else
    start_date
  end,
  end_date = case when $4 is not null then
    $4::date
  else
    end_date
  end
where
  id = $5::uuid
returning
  id, name, budget, start_date, end_date, created_at, updated_at
`

type CrmUpdateCampaignParams struct {
	Name      string         `db:"name" json:"name"`
	Budget    pgtype.Numeric `db:"budget" json:"budget"`
	StartDate pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date    `db:"end_date" json:"end_date"`
	ID        pgtype.UUID    `db:"id" json:"id"`
}

func (q *Queries) CrmUpdateCampaign(ctx context.Context, arg CrmUpdateCampaignParams) (CrmCampaign, error) {
	row := q.db.QueryRow(ctx, crmUpdateCampaign,
		arg.Name,
		arg.Budget,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i CrmCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Budget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
