// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wms_suppliers.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const wmsAnySupplier = `-- name: WmsAnySupplier :many
select
  id, name, contact_person, email, phone_number, created_at, updated_at, products
from
  "wms"."suppliers_view"
where
  id = any ($1::uuid[])
`

func (q *Queries) WmsAnySupplier(ctx context.Context, ids []pgtype.UUID) ([]WmsSuppliersView, error) {
	rows, err := q.db.Query(ctx, wmsAnySupplier, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WmsSuppliersView
	for rows.Next() {
		var i WmsSuppliersView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactPerson,
			&i.Email,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Products,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wmsFindSupplier = `-- name: WmsFindSupplier :one
select
  id, name, contact_person, email, phone_number, created_at, updated_at, products
from
  "wms"."suppliers_view"
where
  id = $1::uuid
`

func (q *Queries) WmsFindSupplier(ctx context.Context, id pgtype.UUID) (WmsSuppliersView, error) {
	row := q.db.QueryRow(ctx, wmsFindSupplier, id)
	var i WmsSuppliersView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Products,
	)
	return i, err
}

const wmsInsertSupplier = `-- name: WmsInsertSupplier :one
insert into "wms"."suppliers"(name, contact_person, email, phone_number)
  values ($1, $2, $3, $4)
returning
  id, name, contact_person, email, phone_number, created_at, updated_at
`

type WmsInsertSupplierParams struct {
	Name          string      `db:"name" json:"name"`
	ContactPerson pgtype.Text `db:"contact_person" json:"contact_person"`
	Email         pgtype.Text `db:"email" json:"email"`
	PhoneNumber   pgtype.Text `db:"phone_number" json:"phone_number"`
}

func (q *Queries) WmsInsertSupplier(ctx context.Context, arg WmsInsertSupplierParams) (WmsSupplier, error) {
	row := q.db.QueryRow(ctx, wmsInsertSupplier,
		arg.Name,
		arg.ContactPerson,
		arg.Email,
		arg.PhoneNumber,
	)
	var i WmsSupplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const wmsPaginateSupplier = `-- name: WmsPaginateSupplier :many
select
  id, name, contact_person, email, phone_number, created_at, updated_at, products
from
  "wms"."suppliers_view" as suppliers
where (name ilike $1::text
  or email ilike $1::text
  or $1::text is null)
limit $3::int offset ($2::int - 1) * $3::int
`

type WmsPaginateSupplierParams struct {
	Search  pgtype.Text `db:"search" json:"search"`
	Page    int32       `db:"page" json:"page"`
	PerPage int32       `db:"per_page" json:"per_page"`
}

func (q *Queries) WmsPaginateSupplier(ctx context.Context, arg WmsPaginateSupplierParams) ([]WmsSuppliersView, error) {
	rows, err := q.db.Query(ctx, wmsPaginateSupplier, arg.Search, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WmsSuppliersView
	for rows.Next() {
		var i WmsSuppliersView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactPerson,
			&i.Email,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Products,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wmsPaginateSupplierMetadata = `-- name: WmsPaginateSupplierMetadata :one
select
  count(*) over () as total_items,
  ceil(count(*) over ()::numeric / NULLIF($1::int, 0)) as total_pages,
  $2::int as page,
  $1::int as per_page
from
  "wms"."suppliers_view" as suppliers
`

type WmsPaginateSupplierMetadataParams struct {
	PerPage int32 `db:"per_page" json:"per_page"`
	Page    int32 `db:"page" json:"page"`
}

type WmsPaginateSupplierMetadataRow struct {
	TotalItems int64   `db:"total_items" json:"total_items"`
	TotalPages float64 `db:"total_pages" json:"total_pages"`
	Page       int32   `db:"page" json:"page"`
	PerPage    int32   `db:"per_page" json:"per_page"`
}

func (q *Queries) WmsPaginateSupplierMetadata(ctx context.Context, arg WmsPaginateSupplierMetadataParams) (WmsPaginateSupplierMetadataRow, error) {
	row := q.db.QueryRow(ctx, wmsPaginateSupplierMetadata, arg.PerPage, arg.Page)
	var i WmsPaginateSupplierMetadataRow
	err := row.Scan(
		&i.TotalItems,
		&i.TotalPages,
		&i.Page,
		&i.PerPage,
	)
	return i, err
}

const wmsRangeSupplier = `-- name: WmsRangeSupplier :many
select
  id, name, contact_person, email, phone_number, created_at, updated_at, products
from
  "wms"."suppliers_view"
where
  created_at >= $1::date
  and created_at <= $2::date
  and (name ilike $3::text
    or email ilike $3::text
    or $3::text is null)
`

type WmsRangeSupplierParams struct {
	Datefrom pgtype.Date `db:"datefrom" json:"datefrom"`
	Dateto   pgtype.Date `db:"dateto" json:"dateto"`
	Search   pgtype.Text `db:"search" json:"search"`
}

func (q *Queries) WmsRangeSupplier(ctx context.Context, arg WmsRangeSupplierParams) ([]WmsSuppliersView, error) {
	rows, err := q.db.Query(ctx, wmsRangeSupplier, arg.Datefrom, arg.Dateto, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WmsSuppliersView
	for rows.Next() {
		var i WmsSuppliersView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactPerson,
			&i.Email,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Products,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wmsRemoveSupplier = `-- name: WmsRemoveSupplier :exec
delete from "wms"."suppliers"
where id = $1::uuid
`

func (q *Queries) WmsRemoveSupplier(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, wmsRemoveSupplier, id)
	return err
}

const wmsUpdateSupplier = `-- name: WmsUpdateSupplier :one
update
  "wms"."suppliers"
set
  updated_at = now(),
  name = case when $1 is not null then
    $1::varchar
  else
    name
  end,
  contact_person = case when $2 is not null then
    $2::varchar
  else
    contact_person
  end,
  email = case when $3 is not null then
    $3::varchar
  else
    email
  end,
  phone_number = case when $4 is not null then
    $4::varchar
  else
    phone_number
  end
where
  id = $5::uuid
returning
  id, name, contact_person, email, phone_number, created_at, updated_at
`

type WmsUpdateSupplierParams struct {
	Name          string      `db:"name" json:"name"`
	ContactPerson pgtype.Text `db:"contact_person" json:"contact_person"`
	Email         pgtype.Text `db:"email" json:"email"`
	PhoneNumber   pgtype.Text `db:"phone_number" json:"phone_number"`
	ID            pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) WmsUpdateSupplier(ctx context.Context, arg WmsUpdateSupplierParams) (WmsSupplier, error) {
	row := q.db.QueryRow(ctx, wmsUpdateSupplier,
		arg.Name,
		arg.ContactPerson,
		arg.Email,
		arg.PhoneNumber,
		arg.ID,
	)
	var i WmsSupplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
