/**
 * Auto-generated Zod schema for DeliveryManagementProofOfDeliveries
 * Generated by: scripts/generate-zod-schemas.ts
 * DO NOT EDIT MANUALLY
 */

import { z } from "zod";
import { Collections } from "@/lib/pb.types";
import { Coordinates } from "@/pocketbase/scalar";

export const ProofOfDeliveriesSchema = z
  .object({
    id: z.string(),
    task: z.string().optional(),
    signatureData: z.any().optional(),
    recipientName: z.string().optional(),
    coordinates: Coordinates.optional(),
    timestamp: z.iso.datetime().optional(),
  })
  .superRefine((data, ctx) => {
    // POD Requirement: Proof of delivery record must be created before task can transition to 'delivered'
    if (!data.task) {
      ctx.addIssue({
        code: "custom",
        path: ["task"],
        message: "POD must be linked to a delivery task",
      });
    }

    console.info(
      "✍️ Proof of Delivery: Immutable audit record of delivery confirmation. Signature + GPS coordinates required for valid POD."
    );
  });

export type ProofOfDeliveries = z.infer<typeof ProofOfDeliveriesSchema>;
